item_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path
from main.views import show_main
from main.views import *

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('show_data_product', show_data_product, name='show_data_product'),
    path('create_product', create_product, name='create_product'),
    path('edit-product/<int:id>', edit_product, name='edit_product'),
    path('delete/<int:id>', delete_product, name='delete_product'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),

    path('get-product-byID/', get_product_json_byID, name='get_product_json_byID'),
    path('get-product/', get_product_json, name='get_product_json'),
    path('create-product-ajax/', add_product_ajax, name='add_product_ajax'),

    path('create-flutter/', create_product_flutter, name='create_product_flutter'),

]

main/models.py
from django.db import models
from django.contrib.auth.models import User

class Product(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    amount = models.IntegerField()
    date_added = models.DateField(auto_now_add=True)
    description = models.TextField()

main/forms.py
from django.forms import ModelForm
from main.models import Product

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ["name", "amount", "description"]

main/views.py
import datetime
import json

from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponseNotFound, JsonResponse
from main.forms import ProductForm
from django.urls import reverse
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages  
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from django.views.decorators.csrf import csrf_exempt

from main.models import Product

@login_required(login_url='/login')
def create_product(request):
    form = ProductForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        product = form.save(commit=False)
        product.user = request.user
        product.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "create_product.html", context)

def show_main(request):
    products = Product.objects.all()
    last_login = request.COOKIES.get('last_login', '')
    context = {
        'name': request.user.username,
        'class': 'PBP E', # Kelas PBP kamu
        'products': products,
        'last_login': last_login,
    }

    return render(request, "main.html", context)

def show_data_product(request):
    products = Product.objects.filter(user=request.user.id)
    last_login = request.COOKIES.get('last_login', '')
    context ={
        'name': request.user.username,
        'class': 'PBP E', # Kelas PBP kamu
        'products': products,
        'last_login': last_login,
    }

    return render(request, "show_data_product.html", context)

def get_product_json(request):
    product_item = Product.objects.all()
    return HttpResponse(serializers.serialize('json', product_item))

def get_product_json_byID(request):
    product_item_byid = Product.objects.filter(user=request.user.id)
    return HttpResponse(serializers.serialize('json', product_item_byid))

@csrf_exempt
def add_product_ajax(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        amount = request.POST.get("amount")
        description = request.POST.get("description")
        user = request.user

        new_product = Product(name=name, amount=amount, description=description, user=user)
        new_product.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

def edit_product(request, id):
    # Get product berdasarkan ID
    product = Product.objects.get(pk = id)

    # Set product sebagai instance dari form
    form = ProductForm(request.POST or None, instance=product)

    if form.is_valid() and request.method == "POST":
        # Simpan form dan kembali ke halaman awal
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "edit_product.html", context)

def delete_product(request, id):
    # Get data berdasarkan ID
    product = Product.objects.get(pk = id)
    # Hapus data
    product.delete()
    # Kembali ke halaman awal
    return HttpResponseRedirect(reverse('main:show_data_product'))

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def show_xml(request):
    data = Product.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_xml_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Product.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_json_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_product = Product.objects.create(
            user = request.user,
            name = data["name"],
            amount = int(data["amount"]),
            description = data["description"]
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/create_product.html
{% extends 'base.html' %} 
{% load static %}

{% block meta %}
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'main.css' %}">
{% endblock meta %}

{% block content %}
<nav class="navbar bg-body-tertiary d-flex justify-content-between">
    <div class="navbar-menu d-flex justify-content-start align-items-center">
        <div class="navbar-header position-relative d-flex justify-content-start align-items-center gap-3 mt-2 mb-2 me-3">
            <img src="{% static 'pictures/fasilkom.png' %}" alt="" class="logo-fasilkom my-auto">
            <a class="navbar-header-text text-decoration-none" href="{% url 'main:show_main' %}"><p class="fw-bold my-auto">Carousell PBP</p></a>
        </div>
        <div class="d-flex flex-row">
            <a href="{% url 'main:show_data_product' %}">
                <button type="button" class="btn btn-light h-100">Data Product</button>
            </a>
            <a href="{% url 'main:create_product' %}">
                <button type="button" class="btn btn-light">Add Product</button>
            </a>
            </div>
        </div>
    </div>

    <div class="">
        <li class="nav-item dropdown">
            <button class="btn  dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                <span id="navbar-user">Hallo, {{name}}</span>
            </button>
            <ul class="dropdown-menu">
                <li class="dropdown-item">Kelas {{class}}</li>
                <li><a class="dropdown-item" href="">Edit Profile</a></li>
                <li><a class="dropdown-item" href="{% url 'main:logout' %}">Logout</a></li>
            </ul>
        </li>
    </div>
</nav>
<h1>Add New Product</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Add Product"/>
            </td>
        </tr>
    </table>
</form>

{% endblock %}

main/templates/edit_product.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'main.css' %}">
{% endblock meta %}

{% block content %}
<nav class="navbar bg-body-tertiary d-flex justify-content-between">
    <div class="navbar-menu d-flex justify-content-start align-items-center">
        <div class="navbar-header position-relative d-flex justify-content-start align-items-center gap-3 mt-2 mb-2 me-3">
            <img src="{% static 'pictures/fasilkom.png' %}" alt="" class="logo-fasilkom my-auto">
            <a class="navbar-header-text text-decoration-none" href="{% url 'main:show_main' %}"><p class="fw-bold my-auto">Carousell PBP</p></a>
        </div>
        <div class="d-flex flex-row">
            <a href="{% url 'main:show_data_product' %}">
                <button type="button" class="btn btn-light h-100">Data Product</button>
            </a>
            <a href="{% url 'main:create_product' %}">
                <button type="button" class="btn btn-light">Add Product</button>
            </a>
            </div>
        </div>
    </div>

    <div class="">
        <li class="nav-item dropdown">
            <button class="btn  dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                <span id="navbar-user">Hallo, {{name}}</span>
            </button>
            <ul class="dropdown-menu">
                <li class="dropdown-item">Kelas {{class}}</li>
                <li><a class="dropdown-item" href="">Edit Profile</a></li>
                <li><a class="dropdown-item" href="{% url 'main:logout' %}">Logout</a></li>
            </ul>
        </li>
    </div>
</nav>

<h1>Edit Product</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Edit Product"/>
            </td>
        </tr>
    </table>
</form>

{% endblock %}

main/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'login.css' %}">
{% endblock meta %}

{% block content %}

<div class="container min-vh-100 d-flex justify-content-center align-items-center" style="height: 70%; width: 70%;">
    <div class="card">
        <div class="card-header d-flex justify-content-start align-items-center mt-2 mb-2 bg-white">
            <!-- cara add image gimana? -->
            <img src="{% static 'pictures/fasilkom.png' %}" alt="" class="logo-fasilkom">
            <!-- <div class="custom-circle me-3" style="width: 15px; height: 15px;"></div> -->
            <h5>Carousell PBP</h5>
        </div>
        <div class="card-body">
            <form form method="POST" action="">
                {% csrf_token %}
                <div>
                    <div class="mb-3">
                      <label class="form-label">Username</label>
                      <input type="text" name="username" placeholder="Username" class="form-control">
                    </div>
                    
                    <div class="">
                      <label for="exampleInputPassword1" class="form-label">Password</label>
                      <input type="password" name="password" placeholder="Password" class="form-control">
                    
                    </div>
                    <div class="">
                        {% if messages %}
                            <p class="text-danger">Wrong Password</p>
                        {% endif %}
                    </div>
                    
                </div>
                <button type="submit" class="btn btn-primary mt-3" style="width: 100%;">Login</button>
            </form>
            <div class="mt-3">          
                Don't have an account yet? <a href="{% url 'main:register' %}">Register Now</a>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'main.css' %}">
{% endblock meta %}

{% block content %}
<nav class="navbar bg-body-tertiary d-flex justify-content-between">
    <div class="navbar-menu d-flex justify-content-start align-items-center">
        <div class="navbar-header position-relative d-flex justify-content-start align-items-center gap-3 mt-2 mb-2 me-3">
            <img src="{% static 'pictures/fasilkom.png' %}" alt="" class="logo-fasilkom my-auto">
            <a class="navbar-header-text text-decoration-none" href="{% url 'main:show_main' %}"><p class="fw-bold my-auto">Carousell PBP</p></a>
        </div>
        <div class="d-flex flex-row">
            <a href="{% url 'main:show_data_product' %}">
                <button type="button" class="btn btn-light h-100">Data Product</button>
            </a>
            <a href="{% url 'main:create_product' %}">
                <button type="button" class="btn btn-light">Add Product</button>
            </a>
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">Add Product by AJAX</button>      
            </div>
        </div>
    </div>

    <div class="">
        <li class="nav-item dropdown">
            <button class="btn  dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                <span id="navbar-user">Hallo, {{name}}</span>
            </button>
            <ul class="dropdown-menu">
                <li class="dropdown-item">Kelas {{class}}</li>
                <li><a class="dropdown-item" href="">Edit Profile</a></li>
                <li><a class="dropdown-item" href="{% url 'main:logout' %}">Logout</a></li>
            </ul>
        </li>
    </div>
</nav>


<div id="product_content" class="all-product d-flex flex-wrap align-content-start gap-4">
    <!-- GANTI DENGAN AJAX
    {% for product in products %}
    <div class="card" style="width: 18rem;">
        <img src="{% static 'pictures/product1.jpg' %}" class="card-img-top" alt="">
        <div class="card-body">
          <h5 class="card-title">{item.fields.name}</h5>
          <p class="card-harga">Rp.{item.fields..amount}</p>
          <p class="card-text">{item.fields.description}</p>
          <a href="#" class="btn btn-primary" style="width: 100%;">Beli Sekarang</a>
        </div>
    </div>
    {% endfor %} -->
</div>


<h5>Sesi terakhir login: {{ last_login }}</h5>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Product</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="form" onsubmit="return false;">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="name" class="col-form-label">Name:</label>
                        <input type="text" class="form-control" id="name" name="name"></input>
                    </div>
                    <div class="mb-3">
                        <label for="amount" class="col-form-label">Amount:</label>
                        <input type="number" class="form-control" id="amount" name="amount"></input>
                    </div>
                    <div class="mb-3">
                        <label for="description" class="col-form-label">Description:</label>
                        <textarea class="form-control" id="description" name="description"></textarea>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Product</button>
            </div>
        </div>
    </div>
</div>

<script>
    async function getProducts() {
        return fetch("{% url 'main:get_product_json' %}").then((res) => res.json())
    }
    async function refreshProducts() {
    document.getElementById("product_content").innerHTML = ""
    const products = await getProducts()
    let htmlString = ``
    products.forEach((item) => {
        htmlString += `\n
        <div class="card" style="width: 18rem;">
            <img src="{% static 'pictures/product1.jpg' %}" class="card-img-top" alt="">
            <div class="card-body">
                <h5 class="card-title">${item.fields.name}</h5>
                <p class="card-harga">Rp.${item.fields.amount}</p>
                <p class="card-text">${item.fields.description}</p>
                <a href="#" class="btn btn-primary" style="width: 100%;">Beli Sekarang</a>
            </div>
        </div>` 
    })
    
    document.getElementById("product_content").innerHTML = htmlString
    }

    refreshProducts()

    function addProduct() {
            fetch("{% url 'main:add_product_ajax' %}", {
                method: "POST",
                body: new FormData(document.querySelector('#form'))
            }).then(refreshProducts)

            document.getElementById("form").reset()
            return false
        }

    document.getElementById("button_add").onclick = addProduct
</script>
{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>Register</title>
{% endblock meta %}

{% block content %}
<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h1 class="text-center">Register</h1>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <div class="text-center">
                            <button type="submit" class="btn btn-primary">Daftar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    {% if messages %}
    <div class="row mt-3">
        <div class="col-md-6">
            <div class="alert alert-danger">
                <ul>
                    {% for message in messages %}
                    <li>{{ message }}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
    {% endif %}
</div>
{% endblock content %}

main/templates/show_data_product.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'show_data_product.css' %}">
{% endblock meta %}

{% block content %}
<nav class="navbar bg-body-tertiary d-flex justify-content-between">
    <div class="navbar-menu d-flex justify-content-start align-items-center">
        <div class="navbar-header position-relative d-flex justify-content-start align-items-center gap-3 mt-2 mb-2 me-3">
            <img src="{% static 'pictures/fasilkom.png' %}" alt="" class="logo-fasilkom my-auto">
            <a class="navbar-header-text text-decoration-none" href="{% url 'main:show_main' %}"><p class="fw-bold my-auto">Carousell PBP</p></a>
        </div>
        <div class="d-flex flex-row">
            <a href="{% url 'main:show_data_product' %}">
                <button type="button" class="btn btn-light h-100">Data Product</button>
            </a>
            <a href="{% url 'main:create_product' %}">
                <button type="button" class="btn btn-light">Add Product</button>
            </a>
            </div>
        </div>
    </div>

    <div class="">
        <li class="nav-item dropdown">
            <button class="btn  dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                <span id="navbar-user">Hallo, {{name}}</span>
            </button>
            <ul class="dropdown-menu">
                <li class="dropdown-item">Kelas {{class}}</li>
                <li><a class="dropdown-item" href="">Edit Profile</a></li>
                <li><a class="dropdown-item" href="{% url 'main:logout' %}">Logout</a></li>
            </ul>
        </li>
    </div>

</nav>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>Name</th>
            <th>Price</th>
            <th>Description</th>
            <th>Date Added</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody id="product_table">
        
    </tbody>
</table>


    <br />

    <h5>Sesi terakhir login: {{ last_login }}</h5>

<script>
    async function getProductsID() {
        return fetch("{% url 'main:get_product_json_byID' %}").then((res) => res.json())
    }

    async function refreshProducts(){
        document.getElementById("product_table").innerHTML= ""
        const products = await getProductsID();
        let htmlString =``

        products.forEach((item) => {
            htmlString += `
                <tr>
                    <td>${ item.fields.name }</td>
                    <td>${ item.fields.amount }</td>
                    <td>${ item.fields.description }</td>
                    <td>${ item.fields.date_added }</td>
                    <td>
                        <button href="#" class="btn btn-primary btn-sm edit-product" data-id="${item.pk}">
                            Edit
                        </button>
                        <button href="#" class="btn btn-danger btn-sm delete-product" data-id="${item.pk}">
                            Delete
                        </button>
                    </td>
                </tr>
            `
        });

        document.getElementById("product_table").innerHTML = htmlString;

        document.querySelectorAll('.edit-product').forEach(button => {
        button.addEventListener('click', function () {
            // Dapatkan ID produk dari atribut data-id tombol yang diklik
            const productId = button.getAttribute('data-id');

            // Buat URL yang sesuai dengan permintaan Anda (misalnya, URL untuk mengedit produk)
            const editUrl = `/edit-product/${productId}`;

            // Navigasikan ke URL editUrl
            window.location.href = editUrl;
            });
        });

        // Tambahkan event listener untuk tombol "Delete"
        document.querySelectorAll('.delete-product').forEach(button => {
            button.addEventListener('click', function () {
                // Dapatkan ID produk dari atribut data-id tombol yang diklik
                const productId = button.getAttribute('data-id');

                // Buat URL yang sesuai dengan permintaan Anda (misalnya, URL untuk menghapus produk)
                const deleteUrl = `/delete/${productId}`;

                // Navigasikan ke URL deleteUrl
                window.location.href = deleteUrl;
            });
        });
    }
    refreshProducts();
</script>
    

{% endblock content %}